import Header from "@/components/header/Header";
import "./globals.scss";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Footer from "@/components/Footer/Footer";
import ProviderRedux from "@/Redux/Provider/ProviderRedux";
import { StrictMode } from "react";
import ProviderClient from "@/ProviderClient/ProviderClient";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <StrictMode>
          <ProviderRedux>
            <>
              <Header />
              <ProviderClient>{children}</ProviderClient>
              <Footer />
            </>
          </ProviderRedux>
        </StrictMode>
      </body>
    </html>
  );
}
